apiVersion: apps/v1
kind: Deployment
metadata:
  name: gls-python-helloworld-app
  labels:
    app: gls-python-helloworld-app
spec:
  replicas: 3
      containers:
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 50m
              memory: 128Mi
