---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod-gls-interview

resources:
  - ../../base/gls-python-helloworld-app

images:
  - name: ghcr.io/barissekerciler/gls-python-helloworld-app
    newTag: "v1.0.1" # {"$imagepolicy": "flux-system:prod-gls-python-helloworld-app"}

patches:
  - path: deployment-patch.yaml

namePrefix: prod-

replicas:
  - name: gls-python-helloworld-app
    count: 3
