apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: gls-python-helloworld-app
  namespace: flux-system
spec:
  image: ghcr.io/barissekerciler/gls-python-helloworld-app
  interval: 30s
