apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: staging-gls-python-helloworld-app
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: gls-python-helloworld-app
    namespace: flux-system
  policy:
    semver:
      range: 1.0.0-rc.x
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: prod-gls-python-helloworld-app
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: gls-python-helloworld-app
    namespace: flux-system
  filterTags:
    pattern: "^staging-[a-fA-F0-9]+-(?P<ts>.*)"
    extract: "$ts"
  policy:
    numerical:
      order: asc
